notes: |
  Toont navigatie-tabs. Gebaseerd op de Bootstrap "Navs" component
collated: true
context:
  __title: 2 tabs
  count: 2
  tabs:
    - label: Tab 1
      url: '#'
    - label: Tab 2
      url: '#'
variants:
  - name: Three tabs
    context:
      __title: 3 tabs
      count: 3
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'

  - name: Four tabs
    context:
      __title: Four tabs
      count: 4
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'

  - name: Five tabs
    context:
      __title: Five tabs
      count: 5
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'

  - name: Six tabs
    context:
      __title: Six tabs
      count: 6
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'

  - name: Seven tabs
    context:
      __title: Seven tabs
      count: 7
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'

  - name: Eight tabs
    context:
      __title: Eight tabs
      count: 8
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'

  - name: Nine tabs
    context:
      __title: Nine tabs
      count: 9
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'

  - name: Ten tabs
    context:
      __title: Ten tabs
      count: 10
      tabs:
      - label: Tab 1
        url: '#'
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'
      - label: Tab 10
        url: '#'
